const offcanvas=document.querySelector(".offcanvas");const hamburger=document.querySelector(".navbar-toggler");const stickyTop=document.querySelector(".sticky-top");hamburger.addEventListener("click",function(){stickyTop.style.overflow="visible"});offcanvas.addEventListener("hidden.bs.offcanvas",function(){stickyTop.style.overflow="hidden"});const rootElement=document.querySelector(":root");const audioIconWrapper=document.querySelector(".audio-icon-wrapper");const audioIcon=document.querySelector(".audio-icon-wrapper i");const song=document.querySelector("#song");let isPlaying=!1;function disableScroll(){const scrollTop=window.pageYOffset||document.documentElement.scrollTop;const scrollLeft=window.pageXOffset||document.documentElement.scrollLeft;window.onscroll=function(){window.scrollTo(scrollTop,scrollLeft)};rootElement.style.scrollBehavior="auto"}
function enableScroll(){window.onscroll=function(){};rootElement.style.scrollBehavior="smooth";playAudio()}
function playAudio(){song.volume=0.03;audioIconWrapper.style.display="flex";song.play();isPlaying=!0}
audioIconWrapper.addEventListener("click",function(){if(isPlaying){song.pause();audioIcon.classList.remove("bi-disc");audioIcon.classList.add("bi-pause-circle")}else{song.play();audioIcon.classList.add("bi-disc");audioIcon.classList.remove("bi-pause-circle")}
isPlaying=!isPlaying});disableScroll();window.addEventListener("load",function(){const form=document.getElementById("my-form");if(form){form.addEventListener("submit",function(e){e.preventDefault();const data=new FormData(form);const action=e.target.action;fetch(action,{method:"POST",body:data}).then(()=>{alert("Konfirmasi kehadiran berhasil terkirim!")}).catch((error)=>{alert("Terjadi kesalahan saat mengirim data. Silakan coba lagi.")})})}
const urlParams=new URLSearchParams(window.location.search);const nama=urlParams.get("n")||"";const pronoun=urlParams.get("p")||"Bapak/Ibu/Saudara/i";const namaContainer=document.querySelector(".hero h4 span");if(namaContainer){namaContainer.innerText=`${pronoun} ${nama},`.replace(/ ,$/,",")}
const namaInput=document.querySelector("#nama");if(namaInput){namaInput.value=nama}
const offcanvasNavbar=document.getElementById("offcanvasNavbar");const navLinks=document.querySelectorAll(".nav-link");const bsOffcanvas=new bootstrap.Offcanvas(offcanvasNavbar);navLinks.forEach((link)=>{link.addEventListener("click",function(){bsOffcanvas.hide()})});AOS.init({once:!1})});function copyText(element){const textToCopy=element.parentElement.querySelector(".number").innerText;const textarea=document.createElement("textarea");textarea.value=textToCopy;document.body.appendChild(textarea);textarea.select();textarea.setSelectionRange(0,99999);document.execCommand("copy");document.body.removeChild(textarea);$(element).html("Berhasil disalin!");setTimeout(function(){$(element).html('<i class="fas fa-fw fa-copy"></i> Copy')},2000)}
document.getElementById("my-form")?.addEventListener("submit",function(event){const statusSelect=document.getElementById("status");if(statusSelect.value===""){event.preventDefault();alert("Konfirmasi wajib dipilih!")}});$(document).ready(function(){$('a[href="#gift"]').on("click",function(event){event.preventDefault();$("html, body").animate({scrollTop:$("#gift").offset().top-200},100)})})
